EnsimagCafet.Web/Controllers/CultureController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace EnsimagCafet.Web.Controllers
{
    [Route("[controller]")]
    public sealed class CultureController : Controller
    {
        [HttpPost("set")]
        [AllowAnonymous]
        public IActionResult Set(string culture, string redirectUri)
        {
            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName, CookieRequestCultureProvider.MakeCookieValue(new(culture)));
            return LocalRedirect(redirectUri);
        }
    }
}

EnsimagCafet.Web/Views/Shared/_CulturePartial.cshtml
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@inject IViewLocalizer localizer
@inject IOptions<RequestLocalizationOptions> locOptions

@{
    var currentCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultures = locOptions.Value.SupportedUICultures?.Select(x => new SelectListItem { Value = x.Name, Text = x.Name }).ToList();
    var redirectUri = string.IsNullOrWhiteSpace(Context.Request.Path) ? "~/" : $"~{Context.Request.Path}{Context.Request.QueryString}";
}

@if (currentCulture is not null && cultures is not null)
{
    <div class="d-flex ms-1 ms-lg-3">
        <a href="#" class="btn btn-icon btn-active-light-primary btn-icon-light btn-custom w-30px h-30px w-md-40px h-md-40px" data-kt-menu-trigger="{default:'click', lg: 'hover'}" data-kt-menu-attach="parent" data-kt-menu-placement="bottom-end">
            <span class="menu-icon" data-kt-element="icon">
                <span class="svg-icon svg-icon-xl-1">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512" fill="none"><path d="M0 128C0 92.7 28.7 64 64 64H256h48 16H576c35.3 0 64 28.7 64 64V384c0 35.3-28.7 64-64 64H320 304 256 64c-35.3 0-64-28.7-64-64V128zm320 0V384H576V128H320zM178.3 175.9c-3.2-7.2-10.4-11.9-18.3-11.9s-15.1 4.7-18.3 11.9l-64 144c-4.5 10.1 .1 21.9 10.2 26.4s21.9-.1 26.4-10.2l8.9-20.1h73.6l8.9 20.1c4.5 10.1 16.3 14.6 26.4 10.2s14.6-16.3 10.2-26.4l-64-144zM160 233.2L179 276H141l19-42.8zM448 164c11 0 20 9 20 20v4h44 16c11 0 20 9 20 20s-9 20-20 20h-2l-1.6 4.5c-8.9 24.4-22.4 46.6-39.6 65.4c.9 .6 1.8 1.1 2.7 1.6l18.9 11.3c9.5 5.7 12.5 18 6.9 27.4s-18 12.5-27.4 6.9l-18.9-11.3c-4.5-2.7-8.8-5.5-13.1-8.5c-10.6 7.5-21.9 14-34 19.4l-3.6 1.6c-10.1 4.5-21.9-.1-26.4-10.2s.1-21.9 10.2-26.4l3.6-1.6c6.4-2.9 12.6-6.1 18.5-9.8l-12.2-12.2c-7.8-7.8-7.8-20.5 0-28.3s20.5-7.8 28.3 0l14.6 14.6 .5 .5c12.4-13.1 22.5-28.3 29.8-45H448 376c-11 0-20-9-20-20s9-20 20-20h52v-4c0-11 9-20 20-20z" fill="currentColor" /></svg>
                </span>
            </span>
        </a>
        <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-title-gray-700 menu-icon-muted menu-active-bg menu-state-color fw-semibold py-4 fs-base w-175px" data-kt-menu="true">
            @foreach (var culture in cultures)
            {
                @if (culture.Value == currentCulture.RequestCulture.UICulture.Name)
                {
                    <div class="menu-item px-3 my-0">
                        <form asp-controller="Culture" asp-action="Set" method="post" asp-route-redirectUri="@redirectUri" asp-route-culture="@culture.Value">
                            <button type="submit" class="btn bg-light btn-active-text-primary menu-link px-2 py-1 w-100">
                                <span class="menu-icon" data-kt-element="icon">
                                    <img class="w-15px h-15px rounded-1" src="~/metronic-assets/media/flags/cultures/@(culture.Value).svg" alt="">
                                </span>
                                <small class="text-reset menu-title text-primary m-lg-1">@culture.Text</small>
                            </button>
                        </form>
                    </div>
                }
                else
                {
                    <div class="menu-item px-6 my-0">
                        <form asp-controller="Culture" asp-action="Set" method="post" asp-route-redirectUri="@redirectUri" asp-route-culture="@culture.Value">
                            <button type="submit" class="btn btn-link menu-link px-3 py-2 w-100">
                                <span class="menu-icon" data-kt-element="icon">
                                    <span class="menu-icon" data-kt-element="icon">
                                        <img class="w-15px h-15px rounded-1" src="~/metronic-assets/media/flags/cultures/@(culture.Value).svg" alt="">
                                    </span>
                                </span>
                                <small class="menu-title">@culture.Text</small>
                            </button>
                        </form>
                    </div>
                }
            }
        </div>
    </div>
}

EnsimagCafet.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EnsimagCafet.Web</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700" />
    <link rel="stylesheet" href="~/metronic-assets/plugins/global/plugins.bundle.css">
    <link rel="stylesheet" href="~/metronic-assets/css/style.bundle.css">
    <link rel="stylesheet" href="~/css/custom.css">
    <script src="https://kit.fontawesome.com/40beaa7130.js" crossorigin="anonymous"></script>
</head>
<body id="kt_app_body" class="app-default d-flex" data-kt-app-page-loading-enabled="true" data-kt-app-page-loading="on">
    <script>
        var defaultThemeMode = "dark";
        var themeMode;
        if (document.documentElement) {
            if (document.documentElement.hasAttribute("data-theme-mode")) {
                themeMode = document.documentElement.getAttribute("data-theme-mode");
            } else {
                if (localStorage.getItem("data-theme") !== null) {
                    themeMode = localStorage.getItem("data-theme");
                } else {
                    themeMode = defaultThemeMode;
                }
            }
            if (themeMode === "system") {
                themeMode = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
            }
            document.documentElement.setAttribute("data-theme", themeMode);
        }
    </script>
    <div class="d-flex flex-column flex-root">
        <div class="page d-flex flex-row flex-column-fluid">
            <div class="wrapper d-flex flex-column flex-row-fluid" id="kt_wrapper">
                <header>
                    <nav class="navbar navbar-expand-lg navbar-dark bg-transparent py-4 border-bottom">
                        <div class="container-fluid">
                            <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Cafet' Ensimag</a>
                            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#headerNavbarContent" aria-controls="headerNavbarContent" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="headerNavbarContent">
                                <ul class="navbar-nav me-auto flex-grow-1">
                                    <li class="nav-item">
                                        <a asp-area="" asp-controller="Home" asp-action="Bootstrap" class="mx-1 px-4 btn btn-active-light-primary btn-custom btn-text-light">Bootstrap</a>
                                    </li>
                                </ul>
                                <div>
                                    <partial name="_LoginPartial" />
                                </div>
                                <ul class="navbar-nav me-auto flex-row mx-2">
                                    <li class="nav-item">
                                        <partial name="_CulturePartial" />
                                    </li>
                                    <li class="nav-item">
                                        <partial name="_ThemePartial" />
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </header>
                <div class="container">
                    <main role="main" class="py-3">
                        @RenderBody()
                    </main>
                </div>
                <footer class="border-top footer text-muted">
                    <div class="container">
                        &copy; 2022 - Cafet' Ensimag - Gaspard Andrieu
                    </div>
                </footer>
            </div>
        </div>
    </div>
    <script src="~/metronic-assets/plugins/global/plugins.bundle.js"></script>
    <script src="~/metronic-assets/js/scripts.bundle.js"></script>
    <script src="~/metronic-assets/js/widgets.bundle.js"></script>
    <script src="~/metronic-assets/js/custom/widgets.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>